name: DEPLOY VERSION

on:
 push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: central
        settings-path: ${{ github.workspace }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Test with Maven
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn clean compile --file pom.xml