name: DEPLOY VERSION

on:
 push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh
        settings-path: ${{ github.workspace }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Test with Maven
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn clean compile --file pom.xml

    - name: Deploy Artifact
      run: |
        gpg --batch --gen-key gen-key-script
        uid=$(gpg --list-secret-keys --with-colons | awk -F: '$1 == "sec" {print $5}')
        gpg --keyserver keyserver.ubuntu.com --send-keys $uid
        echo "waiting..."
        sleep 100
        echo "waiting finish!"
        gpg --keyserver keyserver.ubuntu.com --recv-keys $uid
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DpomFile=pom.xml
        gpg --batch --delete-secret-key $id
        gpg --batch --delete-key $id
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    - name: Cleaner
      run: |
        uid=$(gpg --list-secret-keys --with-colons | awk -F: '$1 == "sec" {print $5}')
        gpg --batch --delete-secret-key $id
        gpg --batch --delete-key $id