# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: lib-logbit-package

on:
 push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
      MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      run: | 
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        echo "user: $MAVEN_USERNAME"
      env:
        MAVEN_USERNAME: olá
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Test with Maven
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml